jobs/urls.py
from django.urls import re_path
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.conf.urls.static import static
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from django.views.decorators.csrf import csrf_exempt
from graphene_file_upload.django import FileUploadGraphQLView

from jobs.sitemaps import Sitemaps, StaticViewSitemap
from resume_cv.views import load_builder, update_builder

schema_view = get_schema_view(
    openapi.Info(
        title="Jobs Portal API",
        default_version="v1",
        description="Jobs Portal Api Description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

lang_patterns = i18n_patterns(
    path("", include("jobsapp.urls")),
    path("", include("accounts.urls")),
    path("", include("resume_cv.urls")),
)

# sitemaps = {
#     '': JobViewSitemap
# }

urlpatterns = lang_patterns + [
    re_path(r"^i18n/", include("django.conf.urls.i18n")),
    path("admin/", admin.site.urls),
    path("templates/load-builder/<id>", load_builder, name="resume-cv.load.builder"),
    path("templates/update-builder/<id>", csrf_exempt(update_builder), name="resume-cv.update.builder"),
    path(
        "api/",
        include(
            [
                path("swagger", schema_view.with_ui("swagger", cache_timeout=0)),
                path("", include("accounts.api.urls")),
                path("", include("jobsapp.api.urls")),
                path("", include("tags.api.urls")),
                # path('auth/oauth/', include('rest_framework_social_oauth2.urls'))
            ]
        ),
    ),
    path("social-auth/", include("social_django.urls", namespace="social")),
    # url(r"^(?P<url>.*/)$", flatpages_views.flatpage),
    path("sitemap.xml/", sitemap, {"sitemaps": dict(Sitemaps())}, name="django.contrib.sitemaps.views.sitemap"),
    path("graphql/", csrf_exempt(FileUploadGraphQLView.as_view(graphiql=True))),
]

if settings.ENABLE_PROMETHEUS:
    urlpatterns.append(path("", include("django_prometheus.urls")))

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

jobsapp/urls.py
from django.urls import include, path

from .views import *

app_name = "jobs"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("favorite/", favorite, name="favorite"),
    path("search/", SearchView.as_view(), name="search"),
    path(
        "employer/dashboard/",
        include(
            [
                path("", DashboardView.as_view(), name="employer-dashboard"),
                path("all-applicants/", ApplicantsListView.as_view(), name="employer-all-applicants"),
                path("applicants/<int:job_id>/", ApplicantPerJobView.as_view(), name="employer-dashboard-applicants"),
                path(
                    "applied-applicant/<int:job_id>/view/<int:applicant_id>",
                    AppliedApplicantView.as_view(),
                    name="applied-applicant-view",
                ),
                path("mark-filled/<int:job_id>/", filled, name="job-mark-filled"),
                path("send-response/<int:applicant_id>", SendResponseView.as_view(), name="applicant-send-response"),
                path("jobs/create/", JobCreateView.as_view(), name="employer-jobs-create"),
                path("jobs/<int:id>/edit/", JobUpdateView.as_view(), name="employer-jobs-edit"),
            ]
        ),
    ),
    path(
        "employee/",
        include(
            [
                path("my-applications", EmployeeMyJobsListView.as_view(), name="employee-my-applications"),
                path("favorites", FavoriteListView.as_view(), name="employee-favorites"),
            ]
        ),
    ),
    path("apply-job/<int:job_id>/", ApplyJobView.as_view(), name="apply-job"),
    path("jobs/", JobListView.as_view(), name="jobs"),
    path("jobs/<int:id>/", JobDetailsView.as_view(), name="jobs-detail"),
    path("about-us/", AboutUsView.as_view(), name="about-us"),
]

jobsapp/api/views/employee.py
from rest_framework import status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.generics import CreateAPIView, ListAPIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from jobsapp.api.permissions import IsEmployee
from jobsapp.api.serializers import ApplicantSerializer, AppliedJobSerializer, ApplyJobSerializer, JobSerializer
from jobsapp.models import Applicant, Job


class ApplyJobApiView(CreateAPIView):
    serializer_class = ApplyJobSerializer
    http_method_names = ["post"]
    permission_classes = [IsAuthenticated, IsEmployee]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        headers = self.get_success_headers(serializer.data)
        return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)


class AppliedJobsAPIView(ListAPIView):
    serializer_class = AppliedJobSerializer
    permission_classes = [IsAuthenticated, IsEmployee]

    def get_queryset(self):
        applied_jobs_id = list(Applicant.objects.filter(user=self.request.user).values_list("job_id", flat=True))
        return Job.objects.filter(id__in=applied_jobs_id)


@api_view(["GET"])
@permission_classes([IsAuthenticated, IsEmployee])
def already_applied_api_view(request, job_id):
    is_applied = Applicant.objects.filter(user=request.user, job_id=job_id).exists()
    content = {"is_applied": is_applied}
    return Response(content)

jobsapp/views/employee.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, UpdateView

from accounts.forms import EmployeeProfileUpdateForm
from accounts.models import User
from jobsapp.decorators import user_is_employee
from jobsapp.models import Applicant, Favorite


@method_decorator(login_required(login_url=reverse_lazy("accounts:login")), name="dispatch")
@method_decorator(user_is_employee, name="dispatch")
class EmployeeMyJobsListView(ListView):
    model = Applicant
    template_name = "jobs/employee/my-applications.html"
    context_object_name = "applicants"
    paginate_by = 6

    def get_queryset(self):
        self.queryset = (
            self.model.objects.select_related("job").filter(user_id=self.request.user.id).order_by("-created_at")
        )
        if (
            "status" in self.request.GET
            and len(self.request.GET.get("status")) > 0
            and int(self.request.GET.get("status")) > 0
        ):
            self.queryset = self.queryset.filter(status=int(self.request.GET.get("status")))
        return self.queryset


class EditProfileView(UpdateView):
    model = User
    form_class = EmployeeProfileUpdateForm
    context_object_name = "employee"
    template_name = "jobs/employee/edit-profile.html"
    success_url = reverse_lazy("accounts:employee-profile-update")

    @method_decorator(login_required(login_url=reverse_lazy("accounts:login")))
    @method_decorator(user_is_employee)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
        except Http404:
            raise Http404("User doesn't exists")
        # context = self.get_context_data(object=self.object)
        return self.render_to_response(self.get_context_data())

    def get_object(self, queryset=None):
        obj = self.request.user
        if obj is None:
            raise Http404("Job doesn't exists")
        return obj


@method_decorator(login_required(login_url=reverse_lazy("accounts:login")), name="dispatch")
@method_decorator(user_is_employee, name="dispatch")
class FavoriteListView(ListView):
    model = Favorite
    template_name = "jobs/employee/favorites.html"
    context_object_name = "favorites"

    def get_queryset(self):
        return self.model.objects.select_related("job__user").filter(soft_deleted=False, user=self.request.user)

templates/jobs/employee/edit-profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Edit Profile
{% endblock %}

{% block content %}
    <div class="col-lg-6 offset-3">
        <div class="box">
            <h3 class="heading">Edit Profile</h3>
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger alert-dismissable">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger alert-dismissable">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
            <form action="" method="post">
                {% csrf_token %}
                {% for field in form %}
                    {% if field.name == 'gender' %}

                        <div class="form-group">
                            <label for="gender">Gender</label>
                            <br>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" {% if field.value == 'male' %} checked {% endif %}
                                       type="radio" name="gender" id="male gender"
                                       value="male">
                                <label class="form-check-label" for="male">Male</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" {% if field.value == 'female' %} checked {% endif %}
                                       type="radio" name="gender" id="female"
                                       value="female">
                                <label class="form-check-label" for="female">Female</label>
                            </div>
                        </div>

                    {% else %}

                        <div class="form-group">
                            <label for="id_{{ field.name }}">{{ field.label }}</label>
                            <input type="{{ field.field.widget.input_type }}"
                                   class="form-control"
                                   name="{{ field.name }}"
                                   id="id_{{ field.name }}"
                                   value="{{ field.value }}"
                                   placeholder="{{ field.field.widget.attrs.placeholder }}">
                        </div>

                    {% endif %}
                {% endfor %}
                <div class="text-center">
                    <button type="submit" class="btn btn-outline-white-primary">
                        <i class="fa fa-signing"></i> Update
                    </button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/jobs/employee/favorites.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Favorite List
{% endblock %}

{% block content %}
    <section class="bg-light-gray">
        <div class="container">
            <h3 class="heading">Wish list</h3>
            {% if favorites.count > 0 %}
                {% for trending in favorites %}
                    <div class="job-listing job-listing--last">
                        <div class="row">
                            <div class="col-md-12 col-lg-6">
                                <div class="row">
                                    <div class="col-2">
                                        <img src="{% static 'img/company-1.png' %}"
                                             alt="ShareBoardd " class="img-fluid">
                                    </div>
                                    <div class="col-10">
                                        <h4 class="job__title">
                                            <a href="{% url 'jobs:jobs-detail' trending.job.id %}">{{ trending.job.title }}</a>
                                        </h4>
                                        <p class="job__company">
                                            {{ trending.job.company_name }}
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-10 col-md-3 col-lg-2 ml-auto"><i class="fa fa-map-marker job__location"></i>
                                {{ trending.job.location }}
                            </div>
                            <div class="col-10 col-md-3 col-lg-3 ml-auto">
                                <p>Posted {{ trending.job.created_at|timesince }}</p>
                            </div>
                            <div class="col-sm-12 col-md-2 col-lg-1">
                                <div class="job__star">
                                    <a href="javascript:void(0)" data-toggle="tooltip" data-id="{{ trending.job.id }}"
                                       data-placement="top" title="Saved to favourites"
                                       class="job__star__link favorite">
                                        <i class="fa fa-star"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <h4 class="text-center mb-lg-5">Empty favorite list!</h4>
            {% endif %}
        </div>
    </section>
{% endblock %}


{% block javascripts %}

    <script>
        let csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

        function removeFadeOut(el, speed) {
            var seconds = speed / 1000;
            el.style.transition = "opacity " + seconds + "s ease";

            el.style.opacity = 0;
            setTimeout(function () {
                el.parentNode.removeChild(el);
            }, speed);
        }

        $('.job-listing--last .job__star__link').on('click', function (e) {
            let job_id = $(this).data('id');
            let that = $(this);
            $.ajax({
                type: "POST",
                url: "{% url 'jobs:favorite' %}",
                data: {job_id},
                success: function (res) {
                    if (res.status === "added") {
                        that.addClass('favorite');
                        toastr.success(res.message);
                    } else if (res.status === "removed") {
                        document.activeElement.blur();
                        that.removeClass('favorite');
                        toastr.warning(res.message);
                        removeFadeOut(e.target.parentNode.parentNode.parentNode.parentNode.parentNode, 1000);
                    }
                }
            })
        });
    </script>

{% endblock %}

templates/jobs/employee/my-applications.html
{% extends 'base.html' %}
{% block title %}
    Applicants
{% endblock %}
{% load static %}
{% load is_favorited %}
{% load url_replace %}

{% block styles %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet"/>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-theme/0.1.0-beta.10/select2-bootstrap.min.css"
          rel="stylesheet"/>

    <link rel="stylesheet" href="{% static 'vendor/bootstrap-select/css/bootstrap-select.min.css' %}">
    <style>
        .bootstrap-select .dropdown-menu a {
            color: #000000;
        }
    </style>
{% endblock %}

{% block content %}

    <section class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h1 class="heading">All jobs you have applied</h1>
                </div>
            </div>
        </div>
    </section>
    <section style="margin-top: 0 !important;">
        <div class="container">
            <form id="job-main-form" method="get" action="" class="job-main-form">
                <div class="controls">
                    <div class="row align-items-center">
                        <div class="col-3">
                            <div class="form-group">
                                <select id="status" name="status" class="form-control select2">
                                    <option value="" selected>Select status</option>
                                    <option value="1" {% if request.GET.status == "1" %} selected {% endif %}>Pending
                                    </option>
                                    <option value="2" {% if request.GET.status == "2" %} selected {% endif %}>Accepted
                                    </option>
                                    <option value="3" {% if request.GET.status == "3" %} selected {% endif %}>Rejected
                                    </option>
                                </select>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <button type="submit" class="btn btn-outline-white-primary"><i class="fa fa-magic"></i>
                                    Filter
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            {% for applicant in applicants %}
                <div class="job-listing">
                    <div class="row">
                        <div class="col-md-12 col-lg-6">
                            <div class="row">
                                <div class="col-2">
                                    <img src="{{ applicant.job.user.profile.image }}"
                                         alt="" class="img-fluid">
                                </div>
                                <div class="col-10">
                                    <h4 class="job__title">
                                        <a href="{% url 'jobs:jobs-detail' applicant.job.id %}">{{ applicant.job.title }}</a>
                                        {% if applicant.job.filled %}
                                            (Filled)
                                        {% endif %}
                                    </h4>
                                    <p class="job__company">
                                        <a href="#" style="color: #1b1e21">{{ applicant.job.company_name }}</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-10 col-md-3 col-lg-3 ml-auto">
                            <p>Status: <b>{{ applicant.get_status }}</b></p>
                        </div>
                    </div>
                </div>
            {% endfor %}
            <div class="modal fade" id="myModal">
                <div class="modal-dialog">
                    <div class="modal-content">

                        <div class="modal-header">
                            <h4 class="modal-title">Comment by employer</h4>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>

                        <div class="modal-body">
                            <p class="comment"></p>
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                        </div>

                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                                <li class="page-item">
                                    <a href="?page={{ page_obj.previous_page_number }}"
                                       class="page-link">&laquo;</a>
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                    <a class="page-link">&laquo;</a>
                                </li>
                            {% endif %}
                            {% for i in page_obj.paginator.page_range %}
                                {% if page_obj.number == i %}
                                    <li class="page-item active">
                                        <a class="page-link">{{ i }}</a>
                                    </li>
                                {% else %}
                                    <li class="page-item">
                                        <a href="?{% url_replace 'page' i %}" class="page-link">{{ i }}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <li class="page-item">
                                    <a href="?{% url_replace 'page' page_obj.next_page_number %}"
                                       class="page-link">&raquo;</a>
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                    <a class="page-link">&raquo;</a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

{% block javascripts %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.full.js"></script>

    <script>
        $('.js-select2').select2({
            theme: "bootstrap"
        });

        $('.view-comment').on('click', function () {
            $('#myModal').modal('show');

            $('.modal-body .comment').html($(this).data('comment'));
        })
    </script>

{% endblock %}